### ISSUE TITLE
AttributeError: 'PySide6.QtWidgets.QPushButton' object has no attribute 'setStyleSheet'

### ISSUE THREAD

**Issue by UDBIAWDIF** [UN-GCPDS/qt-material#79]
When running the 'examples\full_features: python main.py --pyside6' given, I encountered the problem of AttributeError: 'PySide6.QtWidgets.QPushButton' object has no attribute 'setStyleSheet':

qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
qt.webenginecontext:

GL Type: disabled
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.5
QSG RHI Backend: D3D11
Using Supported QSG Backend: no
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name python
  *  browser-subprocess-path D:\GreenSoft\Python3.11\Lib\site-packages\PySide6\.\QtWebEngineProcess.exe
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture
  *  disable-gpu
  *  disable-speech-api
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess
  *  enable-threaded-compositing
  *  in-process-gpu
  *  use-gl disabled

qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Traceback (most recent call last):
  File "D:\project\python\qt-material\examples\full_features\main.py", line 207, in <module>
    frame = RuntimeStylesheets()
            ^^^^^^^^^^^^^^^^^^^^
  File "D:\project\python\qt-material\examples\full_features\main.py", line 111, in __init__
    self.show_dock_theme(self.main)
  File "D:\GreenSoft\Python3.11\Lib\site-packages\qt_material-2.13-py3.11.egg\qt_material\__init__.py", line 750, in show_dock_theme
    self.update_buttons()
  File "D:\GreenSoft\Python3.11\Lib\site-packages\qt_material-2.13-py3.11.egg\qt_material\__init__.py", line 627, in update_buttons
    button.setStyleSheet(
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PySide6.QtWidgets.QPushButton' object has no attribute 'setStyleSheet'. Did you mean: 'style_sheet'?

**Comment by cabooster** [comment]
'setStyleSheet'
change to:
            try:
                 button.setStyleSheet(
                f"""
            *{{
            background-color: {color};
            color: {text_color};
            border: none;
            }}"""
            )
            except:
                button.style_sheet = f"""
            *{{
            background-color: {color};
            color: {text_color};
            border: none;
            }}"""
